# Generated by Django 2.1.5 on 2019-11-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_ctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='reason',
            field=models.CharField(default='undocumented', max_length=1000),
        ),
    ]
