# Generated by Django 2.1.5 on 2019-11-23 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profilepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to='profilepage.Extendeduser')),
                ('friend2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to='profilepage.Extendeduser')),
            ],
        ),
    ]
