# Generated by Django 2.1.5 on 2019-11-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_dost_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dost',
            name='money',
            field=models.FloatField(default=0.0),
        ),
    ]
