# Generated by Django 2.2.7 on 2019-11-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sw_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='common_Users',
            new_name='CommonUsers',
        ),
    ]
