# Generated by Django 2.2.7 on 2019-11-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sw_users', '0002_auto_20191106_1830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonUsers',
            new_name='CommonUser',
        ),
    ]
