# Generated by Django 2.2.6 on 2019-11-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sw_users', '0003_auto_20191106_1831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonUser',
        ),
    ]
